#! /usr/bin/python3

import socket
import time
import threading

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.bind(('192.168.168.32', 6969))

sock.listen()
print("listening...")

while True:
    clsock, claddr = sock.accept()
    print(f"{claddr} connected")

    data = clsock.recv(1024)
    if data:
        print(data.decode('utf-8'))

sock.close()


